### ISSUE TITLE
integration with status line plugins

### ISSUE THREAD

**Issue by mahush** [tomtom/tinykeymap_vim#11]
First of all, thanks a lot @tomtom for providing this great plugin here on github 🚀 

Now my issue ;-) I’m using the [lightline plugin](https://github.com/itchyny/lightline.vim) to maintain my status line. Besides other things, vim’s current mode is shown there. It would be great if an active map could also be shown at this place. As of my understanding, as of now, this is not possible in a generic way. The only option available I see is to specify start/stop methods for each map accordingly, but I think this is much more cumbersome than necessary. I would prefer to just use your predefined mappings and integrate with lightline on a more general level.

**Comment by mahush** [comment]
I already helped myself by basically adding a new global variable to this plugin, that provides the active map. See [this PR](https://github.com/tomtom/tinykeymap_vim/pull/12) for details. Based on that I could configure lightline as follows:

```
let g:lightline = {
    \ 'component_function': {
    \   'mode': 'LightlineMode'
    \ },
    \ }

function! LightlineMode()
  return g:tinykeymaps_active !=# '' ? toupper(g:tinykeymaps_active) : lightline#mode()
endfunction

```
`autocmd User TinykeymapsStart,TinykeymapsStop call lightline#update()`

**Comment by tomtom** [comment]
I assume this issue is closed with your pull request? Thank you very much for looking into the code.
