### ISSUE TITLE
support for entering keymap from terminal-job-mode

### ISSUE THREAD

**Issue by mahush** [tomtom/tinykeymap_vim#13]
I would like to activate a keymap when vim is in terminal-job-mode.

Specificly, I would like to do the following:
```
call tinykeymap#EnterMap("windows", g:tinykeymap#map#windows#map, {
            \ 'name': 'windows mode',
            \ 'mode': 't'
            \ })
```
Unfortunately terminal-job-mode is not yet supported here.

**Comment by mahush** [comment]
I'm proposing [this PR](https://github.com/tomtom/tinykeymap_vim/pull/14) so solve that issue. I look forward to your feedback :-)

**Comment by tomtom** [comment]
Since when does VIM support this? Could you please insert a version check?

**Comment by mahush** [comment]
This feature was added with [patch 8.2.1978](https://github.com/vim/vim/commit/957cf67d50516ba98716f59c9e1cb6412ec1535d).

Do you want to have a version check in order to support older vim versions?

**Comment by tomtom** [comment]
I added a check and retained the original code for older versions. Could you please check if this works for you? Thanks.

**Comment by mahush** [comment]
Thank you so much @tomtom for adjusting and integrating my suggestion. I just switched back to your recent version and it works perfectly 🚀
