### ISSUE TITLE
Commands of `<M-*>` mappings are interrupted

### ISSUE THREAD

**Issue by laggardkernel** [tomtom/tinykeymap_vim#9]
```vim
call tinykeymap#Map('windows', '<M-Down>', 'resize -5')
call tinykeymap#Map('windows', '<M-Up>', 'resize +5')
call tinykeymap#Map('windows', '<M-Left>', 'vertical :resize -5')
call tinykeymap#Map('windows', '<M-Right>', 'vertical :resize +5')
```

After the first `<M-*>` pressed, the `<M-*>`  input later doesn't trigger a resizing again. After changing the keymappings to `Arrow` keys, it works as expected.

**Comment by laggardkernel** [comment]
Closed because of inactivity.

**Comment by tomtom** [comment]
I missed that one. Are you on the terminal? What do you mean by `Arrow` keys?

**Comment by laggardkernel** [comment]
It seems `getchar(0)` has problem parsing `<M-Left>` key correctly?

environments

- macOS: 10.14.6
- Terminal: kitty 0.20.3, TERM=xterm-kitty
- nvim: v0.4.4

```
tinykeymap#Call key: 450 1 '<80><fc>^H<80>kl' 8
tinykeymap#ProcessKey handle_key: tmux ['<80><fc>^H<80>kl'] 1
tinykeymap#ProcessKey expr: call TmuxResize("h",5)
tinykeymap#ProcessKey status: 1
tinykeymap#Call status: 1 <80><fc>^H
tinykeymap#Call key: 0 1 '<80><fc>^H' 8
tinykeymap#ProcessKey handle_key: tmux ['<80><fc>^H'] -1
tinykeymap#ProcessKey status: 0
tinykeymap#Call status: 0 <80><fc>^H
```

The first time `getchar(0)` reads `<M-Left>` as `'<80><fc>^H<80>kl'`. While at the 2nd time, it reads `<M-Left>` as `'<80><fc>^H'`.

**Comment by tomtom** [comment]
Yes, meta/alt modifiers cause problems on the terminal. IIRC you can use the `:set` command to work around this (:h set-termcap). Maybe somethink like this could help on the terminal:

    set <M-Left>=<80><fc>^H

But this is an individual solution I won't integrate in the plugin. The best option would be to avoid Meta/Alt modifiers on the terminal -- but this is probably not what you wanted to hear.
